version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gestion_actes_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ton_mot_de_passe
      MYSQL_DATABASE: gestion_actes_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/sql/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: gestion_actes_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/gestion_actes_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: cedyar06
    ports:
      - "8080:8080"

volumes:
  mysql_data: